[package]
name = "epicheck"
version = "0.1.0"
edition = "2024"

[dependencies]
ignore = "*"
rayon = "*"
clap = { version = "*", features = ["derive"] }
paparse = { path = "./crates/paparse" }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
